### ISSUE TITLE
Sharing iP code quality feedback [for @danielk0k]

### ISSUE THREAD

**Issue by soc-se-script** [danielk0k/ip#3]
@danielk0k We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

No easy-to-detect issues :+1: 

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

No easy-to-detect issues :+1: 

### Aspect: Method Length

No easy-to-detect issues :+1: 

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/duke/DukeApplication.java` lines `33-37`](https://github.com/danielk0k/ip/blob/e3abc3434312377828ad7f85f5bbdedfad91182f/src/main/java/duke/DukeApplication.java#L33..L37):

```java

    /**
     * Main method for Duke program.
     *
     * @param args Command line arguments.
     */

```

Example from [`src/main/java/duke/task/Task.java` lines `43-46`](https://github.com/danielk0k/ip/blob/e3abc3434312377828ad7f85f5bbdedfad91182f/src/main/java/duke/task/Task.java#L43..L46):

```java

    /**
     * Return if the task is marked to be deleted.
     * @return True if the task is marked to be deleted, else false.
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message (Subject Only)

No easy-to-detect issues :+1: 

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by danielk0k** [comment]
Issues fix at commit [93c4d2d](https://github.com/danielk0k/ip/tree/93c4d2d7b02c96cca60044e10143a4c7f29abca6)
